spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://sgte-db.postgres.database.azure.com:5432/sgte-db01?sslmode=require&currentSchema=academico,documentos,public,sistema,tramites
spring.datasource.username=superadmin
spring.datasource.password=admin@2026
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Logging para debug de errores
logging.level.com.app.backend=DEBUG
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
server.error.include-message=always
server.error.include-stacktrace=never

#Azure Blob Storage
spring.cloud.azure.storage.blob.container-name=archivos-sgra
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.cloud.azure.storage.blob.connection-string=DefaultEndpointsProtocol=https;AccountName=sgrastorage2026;AccountKey=yNNbt2ImfDaS9wIxT0VwlOR/Zi0RdIgs8iD45maSrBmj1F4Dmk3W5CBPgGSAliCh5ri3pINk8QmV+ASt9nznLQ==;EndpointSuffix=core.windows.net

# Json Web Token
jwt.secret=ClaveSecreta-SistemaGestionTramitesEstudiantes
jwt.expiration=1800000

# Groq AI
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
groq.max-tokens=2048
groq.temperature=0.1
groq.timeout-seconds=10