spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://sgte-db.postgres.database.azure.com:5432/sgte-db01?sslmode=require&currentSchema=academico,documentos,public,sistema,tramites
spring.datasource.username=superadmin
spring.datasource.password=admin@2026
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Logging para debug de errores
logging.level.com.app.backend=DEBUG
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
server.error.include-message=always
server.error.include-stacktrace=never